name: Release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 10

      - name: Dependencies
        run: |
            sudo apt-get update
            sudo apt-get install \
            doxygen \
            xorg-dev \
            dpkg-dev \
            rpm \
 
      - name: Generate release
        run: |
          tools/make_geogram_dist.sh -no-doc

      - name: Copy release files
        run: |
          mkdir Releases
          cp /tmp/GEOGRAM/* Releases/
          cd Releases/
          echo "<H1> Geogram Release </H1>" > index.html
          echo "<ul>"  >> index.html
          for i in `ls` ; do echo '<li> <a href="'$i'">' $i '</a> </li>' >> index.html; done
          echo "</ul>" >> index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Releases
          destination_dir: Releases
