name: Nightly

on:
#  schedule:
#    - cron:  '0 4 * * *'
  workflow_dispatch

jobs:
  DailyValgrind:
    name: ${{ matrix.name }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        config: [Debug, Release]
        include:
          - os: ubuntu-20.04
            name: Linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout data
        uses: actions/checkout@v3
        with:
          repository: BrunoLevy/geogram.data
          path: tests/data

      - name: Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: RobotFramework
        run: |
          pip3 install robotframework
          robot --version || true

################### Linux/MacOS ###############################################

      - name: Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install xorg-dev valgrind

      - name: Configure (Linux/MacOS)
        run: |
          ./configure.sh --with-valgrind
          echo "platform="\
          `./configure.sh --show-platform`-${{ matrix.config }} >> $GITHUB_ENV

      - name: Build (Linux/MacOS)
        run: cd build/${{ env.platform }}; make -j2

      - name: Tests (Linux/MacOs)
        run: |
          build/${{ env.platform }}/tests/runpybot.sh \
          --include=daily_valgrind --with-valgrind \
          tests/
          mkdir reports
          cp log.html report.html robot_status.png reports/

##############################################################################

      - name: Publish tests results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TestsResults-${{matrix.name}}-${{matrix.config}}
          path: |
            report.html
            log.html
            run/**/*.memcheck

      - name: Publish tests results on gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          destination_dir: reports/nightly-${{ matrix.name }}-${{ matrix.config }}

      - name: "Notify tests results"
        uses: andstor/file-existence-action@v2
        with:
          files: "TESTS_SUCCESS"
          fail: true
