name: SmokeTests

on:
  workflow_dispatch

env:
  CTEST_OUTPUT_ON_FAILURE: ON
  CTEST_PARALLEL_LEVEL: 2

jobs:
  ####################
  # Linux / macOS
  ####################

  Unix:
    name: ${{ matrix.name }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]
        config: [Debug, Release]
        include:
          - os: macos-11
            name: macOS
          - os: ubuntu-20.04
            name: Linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Checkout data
        uses: actions/checkout@v2
        with:
          repository: BrunoLevy/geogram.data
          path: tests/data

      - name: Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install \
              xorg-dev

      - name: Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: RobotFramework
        run: |
          pip3 install robotframework
          robot --version || true

      - name: Configure
        run: |
          ./configure.sh

      - name: Build
        run: cd build/`./configure.sh --show-platform`-${{ matrix.config }}; make -j2

      - name: Tests
        run: |
          build/tests/runpybot.sh --include=smoke tests/`./configure.sh --show-platform`-${{ matrix.config }}

      - name: Publish tests results
        uses: actions/upload-artifact@v3
        with:
          name: TestsResults-${{matrix.name}}-${{matrix.config}}
          path: |
            report.html
            log.html

  ####################
  # Windows
  ####################

  Windows:
    name: Windows (${{ matrix.config }})
    runs-on: windows-2022
    env:
      CC: cl.exe
      CXX: cl.exe
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Checkout data
        uses: actions/checkout@v2
        with:
          repository: BrunoLevy/geogram.data
          path: tests/data

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install robotframework
        run: |
          pip install robotframework

      - name: Configure
        run: |
          ./configure.bat

      - name: Build
        run: cmake --build build/Windows --config ${{ matrix.config }}

      - name: Tests
        run: |
          build/Windows/tests/runpybot.bat --config=${{ matrix.config }} --include=smoke tests/

      - name: Publish tests results
        uses: actions/upload-artifact@v3
        with:
          name: TestsResults-Windows-${{matrix.config}}
          path: |
            report.html
            log.html

