name: ValgrindMac

on:
  workflow_dispatch

jobs:
  ValgrindMac:
    name: ${{ matrix.name }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
        config: [Debug]
        include:
          - os: macos-11
            name: macOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout data
        uses: actions/checkout@v3
        with:
          repository: BrunoLevy/geogram.data
          path: tests/data

      - name: Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: RobotFramework
        run: |
          pip3 install robotframework
          robot --version || true

################### Linux/MacOS ###############################################

      - name: Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install xorg-dev

      - name: Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install valgrind

      - name: Configure (Linux/MacOS)
        run: |
          ./configure.sh --with-valgrind
          echo "platform="\
          `./configure.sh --show-platform`-${{ matrix.config }} >> $GITHUB_ENV

      - name: Build (Linux/MacOS)
        run: |
          cd build/${{ env.platform }};\
          make -j2 2>&1 | tee ../../build_log.txt

      - name: Tests (Linux/MacOs)
        run: |
          build/${{ env.platform }}/tests/runpybot.sh \
          --include=daily_valgrind --with-valgrind \
          tests/

#####################################################################

      - name: Publish tests results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mactest-${{matrix.name}}-${{matrix.config}}
          if-no-files-found: ignore
          path: |
            report.html
            log.html
            run/**/*.memcheck
            build_log.txt
            TESTS_SUCCESS

      - name: "Notify tests results"
        uses: andstor/file-existence-action@v2
        with:
          files: "TESTS_SUCCESS"
          fail: true

#############################################################################

  Reports:
    runs-on: ubuntu-latest
    if: always()
    needs: ValgrindMac
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Generate reports from artifacts
        run: |
          ./tools/generate_reports.sh

      - name: Publish reports on gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/mactest
          destination_dir: reports/mactest
